version: '3.9'

services:
  api:
    build: .
    container_name: nest-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: nest-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      restart: always
      ports:
        - '8080:80'
      env_file:
        - .env
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      depends_on:
        - postgres
volumes:
  pgdata:
  pgadmin_data:
